name: Java CI with Docker and Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start PostgreSQL via Docker Compose
        run: docker compose up -d

      - name: Wait for PostgreSQL to be healthy
        run: |
          echo "Waiting for sisimpur-db to be healthy..."
          for i in {1..10}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' sisimpur-db)
            echo "Health status: $status"
            if [ "$status" == "healthy" ]; then
              echo "Database is healthy!"
              break
            fi
            sleep 5
          done

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build gradle
        run: ./gradlew build
